---
Resources: null
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        - AWSRegionArch2AMI
        - AWS::Region
        - - AWSInstanceType2Arch
          - InstanceType
          - Arch
      KeyName: KeyName
      InstanceType: InstanceType
      SecurityGroups:
        - Ec2SecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 50
        - DeviceName: /dev/sdm
          Ebs:
            VolumeSize: 100
